import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F1F5F9',
  },
  header: {
    backgroundColor: '#2544AD',
    paddingVertical: 35,
    alignItems: 'center',
    marginHorizontal: 10,
    marginTop: 10,
    borderRadius: 15,
  },
  headerText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 120,
  },
  subTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#555',
    textAlign: 'center',
    marginTop: 15,
    marginBottom: 15,
  },
  inputContainer: {
    backgroundColor: '#E9F0F8',
    borderRadius: 5,
    borderBottomWidth: 2,
    borderBottomColor: '#2544AD',
    marginBottom: 15,
  },
  nameInput: {
    paddingVertical: 12,
    paddingHorizontal: 15,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#64748B',
    textAlign: 'center',
  },
  textArea: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 20,
    fontSize: 14,
    color: '#333',
    minHeight: 350,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  actionButtonsContainer: {
    marginTop: 20,
    gap: 12,
  },
  deleteButton: {
    backgroundColor: '#DCE6F5',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    elevation: 2,
  },
  deleteButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000',
  },
  saveButton: {
    backgroundColor: '#2544AD',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    elevation: 3,
  },
  saveButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  footerSticky: {
    position: 'absolute',
    bottom: 25,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 15,
  },
  backButton: {
    flex: 1,
    backgroundColor: '#DCE6F5',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    elevation: 2,
  },
  backButtonText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#000',
  },
  seeFoldersButton: {
    flex: 1.2,
    backgroundColor: '#DCE6F5',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    elevation: 2,
  },
  seeFoldersButtonText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#000',
  },
});