import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F1F5F9',
  },
  header: {
    backgroundColor: '#2544AD',
    paddingVertical: 35,
    alignItems: 'center',
    marginHorizontal: 10,
    marginTop: 10,
    borderRadius: 15,
  },
  headerText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  subTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#555',
    textAlign: 'center',
    marginTop: 15,
  },
  resumeText: {
    fontSize: 16,
    color: '#333',
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 5,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  gridContainer: {
    backgroundColor: '#E9F0F8',
    marginHorizontal: 15,
    borderRadius: 10,
    paddingVertical: 20,
  },
  grid: {
    paddingHorizontal: 20,
    gap: 20,
  },
  gridRow: {
    flexDirection: 'row',
    gap: 20,
  },
  noteBox: {
    flex: 1,
    height: 70,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    paddingHorizontal: 5,
  },
  noteBoxSelected: {
    borderWidth: 2,
    borderColor: '#2544AD',
    backgroundColor: '#F0F4FF',
  },
  emptyBox: {
    backgroundColor: 'transparent',
    elevation: 0,
    shadowOpacity: 0,
  },
  noteText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#000',
    textAlign: 'center',
  },
  actionButtonsInline: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 25,
    gap: 15,
  },
  inlineActionButton: {
    flex: 1,
    backgroundColor: '#DCE6F5',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    elevation: 2,
  },
  actionTextInline: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000',
  },
  footerSticky: {
    position: 'absolute',
    bottom: 25,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 20,
  },
  backButton: {
    flex: 1,
    backgroundColor: '#DCE6F5',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    elevation: 3,
  },
  backButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000',
  },
  newNoteButton: {
    flex: 1,
    backgroundColor: '#2544AD',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    elevation: 3,
  },
  newNoteButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#ffffff',
  },
});